### PR TITLE
gradle dependencies

### PR DESCRIPTION
**Pull request by edewit**
Change to use gradle instead of source

### CODE REVIEW

**Comment by edewit** [comment]
@danielpassos better right?

**Comment by danielpassos** [comment]
Here we go

```
[passos]: ~/Development/Projects/AeroGear/aerogear-cordova-cookbook/Shoot [git:master]  
â†’ cordova plugin add git@github.com:edewit/aerogear-oauth2-cordova.git\#gradle-dependencies
Fetching plugin "git@github.com:edewit/aerogear-oauth2-cordova.git" via npm
npm http GET https://registry.npmjs.org/git
npm http 200 https://registry.npmjs.org/git
Fetching from npm failed: No compatible version found: git@'github.com:edewit/aerogear-oauth2-cordova.git'
Valid install targets:
["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
Error: No compatible version found: git@'github.com:edewit/aerogear-oauth2-cordova.git'
Valid install targets:
["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
    at installTargetsError (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:719:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:638:10
    at saved (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by danielpassos** [comment]
Well, well, well Cordova does not accept `git@` only `http://` \o/

**Pull request merged**
