### PR TITLE
remove swift hack

### PR DESCRIPTION
**Pull request by edewit**
After adding the oauth2 plugin there was a need to change settings in the generated xcode project. This has now been replaced with a js script that does these changes after plugin install

### CODE REVIEW

**Comment by edewit** [comment]
@corinnekrych want to have a look?

**Comment by corinnekrych** [comment]
:eyes:

**Comment by corinnekrych** [comment]
@edewit 
Tested on Shoot demo app (ios platform) with cordova 4.3, ios 8.1.3
Build ok but I have a run-time error:
dyld: Library not loaded: @rpath/libswiftCore.dylib

**Comment by corinnekrych** [comment]
@edewit much better with the runtime addition but now i'm hitting an issue because of camera plugin
see: https://gist.github.com/corinnekrych/03fe12a0978387823cba

since @edewit can't reproduce it, @cvasilak would you mind helping us and give it a go?

**Comment by corinnekrych** [comment]
@edewit using Xcode6.2 with ios8.2 removes the camera issues I had.
I cna now take picture and share them with shoot cordova plugin

+1 to merge this PR
I'll open another one for codova-cookbook readme update

**Pull request merged**
