### PR TITLE
change to id

### PR DESCRIPTION
**Pull request by edewit**
fix for [AGCORDOVA-54](https://issues.jboss.org/browse/AGCORDOVA-54)
@corinnekrych like you proposed

### CODE REVIEW

**Comment by edewit** [comment]
@corinnekrych can we merge?

**Comment by corinnekrych** [comment]
@edewit I'm fine with the change
maybe on this PR or another one we should update the README, stating wp8 support plus adding instruction on changing ```your.protocol``` to match the redirect_uri
wdyt?

**Comment by matzew** [comment]
> maybe on this PR or another one we should update the README, stating wp8 support plus adding instruction on changing your.protocol to match the redirect_uri
wdyt?

+1 on adding this info (don't care if this or different PR)

**Comment by corinnekrych** [comment]
Sorry @edewit it's me inversing + and -
+1 to merge it
no need to add extra comment as this Pr remove the need of configuration

**Pull request merged**
