### PR TITLE
Apply some formatter

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@edewit Could you give it a spin?

**Comment by edewit** [comment]
without the aar I get the following exception https://gist.github.com/edewit/ab58ba2012fbeecbf58c

**Comment by danielpassos** [comment]
Hrm I think it's not about the `@aar` it's about some problem in a Android Cordova platform. I've got the same using version 4.0.0. Could you give try using the master?

```
cordova platform add android@master --usegit
```

**Comment by edewit** [comment]
Let's wait for 4.0.0 to be released then we can remove this workaround completely.

**Pull request closed without merging**
