### PR TITLE
fix dependency rename

### PR DESCRIPTION
**Pull request by edewit**
just like the push plugin this dependency was renamed

### CODE REVIEW

**Comment by danielpassos** [comment]
@bleathem Could you give it a spin? Let me know if you need some help!

**Comment by bleathem** [comment]
I tried to verify this in a local project by running:

```
$ cordova plugin add org.jboss.aerogear.cordova.oauth2
```

This however results in an error:

```
Error: EXDEV, cross-device link not permitted '/tmp/git/1439318042706/LICENSE'
    at Object.fs.renameSync (fs.js:548:18)
    at /home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /home/bleathem/.nvm/v0.10.29/lib/node_modules/cordova/node_modules/q/q.js:557:44
```

I think this is caused by [CB-9212](https://issues.apache.org/jira/browse/CB-9212), but I haven't yet had success working around it.

**Comment by edewit** [comment]
@bleathem Yeah I think this 'fix' also has to do with the git support being broken, you can test that this fix works by doing:

```bash
$ cordova plugin add https://github.com/edewit/aerogear-oauth2-cordova.git#dependency_fix
```

**Comment by bleathem** [comment]
Still causes the same problem.  This SO thread has some workarounds while we wait for cordova 5.2.0 to be released:
http://stackoverflow.com/questions/30801307/upgrade-cordova-cannot-install-plugins-from-git-urls-anymore

**Comment by bleathem** [comment]
After cloning the plugin manually and installing via `cordova plugin add ../aerogear-oauth2-cordova/`, should I expect to see the `es6-promise-plugin` plugins listed under the plugins folder?  All I see is:

```
> ls plugins/
fetch.json  org.jboss.aerogear.cordova.oauth2
```

**Comment by danielpassos** [comment]
`cordova plugin add` works for me

```
[passos]: /tmp  
→ cordova create review
→ cd review/

→ cordova plugin add https://github.com/edewit/aerogear-oauth2-cordova.git#dependency_fix
Fetching plugin "https://github.com/edewit/aerogear-oauth2-cordova.git" via git clone
Repository "https://github.com/edewit/aerogear-oauth2-cordova.git" checked out to git ref "dependency_fix".

→ ls plugins/
total 8
drwxr-xr-x   4 passos  wheel   136B Aug 13 16:12 .
drwxr-xr-x   7 passos  wheel   238B Aug 13 16:12 ..
-rw-r--r--   1 passos  wheel   303B Aug 13 16:12 fetch.json
drwxr-xr-x  12 passos  wheel   408B Aug 13 16:12 org.jboss.aerogear.cordova.oauth2
```

**Comment by bleathem** [comment]
@danielpassos you are reporting the same output as I.  My question was whether we should expect to see the `es6-promise-plugin` dependency plugin listed.

**Comment by bleathem** [comment]
I worked through this with @edewit, and he pointed out that the platfrom has to first be added in order for the plugins to install correctly.

This PR looks good; the renamed plugins is installed as expected.

**Pull request merged**
