### PR TITLE
removed android workaround

### PR DESCRIPTION
**Pull request by edewit**
no longer needs gradle to build can do with cordova command line

### CODE REVIEW

**Comment by edewit** [comment]
fixing issue [AGCORDOVA-78](https://issues.jboss.org/browse/AGCORDOVA-78)

**Comment by bleathem** [comment]
If I understand this PR correctly, it brings in the authz dependencies as source files, so they are compiled directly with the plugin?  Creative solution, I like it.  A potential maintenance burden, but we can revert back to the aar dependency once Cordova 4.0 is generally available.
:+1:

**Comment by abstractj** [comment]
@edewit ahoy, how do you plan to make sure that the version running here is the same released from AGDROID? Example: authz from Android 2.1 released. What would be the process to update the plugin after this change?

**Comment by abstractj** [comment]
@secondsun @danielpassos @matzew any thoughts on it?

**Comment by edewit** [comment]
@abstractj copy the tagged source files from the android git repo

**Comment by matzew** [comment]
Isn't the way: Once Android authz gets a new release, our cordova plugin picks that up and eventually gets release as well. and update of the plugin is done via cordova CLI ?

**Comment by edewit** [comment]
@matzew right, picking up the those changes in the plugin means copying in jar and source files.

**Comment by abstractj** [comment]
I'm -1 on it. Not picky if others decide the opposite, but can't agree with it.

**Comment by matzew** [comment]
I think I have also hard times understanding what this PR is actually
buying us.

On Wed, Mar 11, 2015 at 2:48 PM, Bruno Oliveira <notifications@github.com>
wrote:

> I'm -1 on it. Not picky if others decide the opposite, but can't agree
> with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-cordova-oauth2/pull/17#issuecomment-78265618>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by edewit** [comment]
@matzew because the android oauth lib uses layout it can not be included as a jar file, instead aar file format must be used. This is not supported by cordova yet ( it will be in 4.0 of the android platform) that is why we have the 'gradle workaround' atm by including the module as a source dependency we can remove the 'gradle workaround' and make this plugin easier to use.

**Comment by edewit** [comment]
@abstractj why are you -1 on it?

**Comment by matzew** [comment]
> because the android oauth lib uses layout it can not be included as a jar file, instead aar file format must be used
why ? :-)

...

> module as a source dependency

Ah! so, can I point to a the matching tag? (which is identical to what exists on maven central, hopefully)

**Comment by edewit** [comment]
@matzew that is what I did

**Comment by matzew** [comment]
@edewit +1

**Comment by matzew** [comment]
@edewit how does an update to a future release work ? We would have to manually replace update the JARs? That's a bit cumbersome ;-(

**Comment by danielpassos** [comment]
Well, as @edewit told me days ago, the Cordova is about to release a new version to support aar. IMHO the best thing to do is wait a bit for it to kill the workaround. 

I really like to kill the workaround as @edewit is doing in iOS but, I don't like the idea of copy the source code. 

:-1:

**Comment by matzew** [comment]
yeah, the inclusion, and a later update, leads to cumbersome tasks. I don't
like that as well.

On Wed, Mar 11, 2015 at 4:35 PM, Daniel Passos <notifications@github.com>
wrote:

> Well, as @edewit <https://github.com/edewit> told me days ago, the
> Cordova is about to release a new version to support aar. IMHO the best
> thing to do is wait a bit for it to kill the workaround.
>
> I really like to kill the workaround as @edewit
> <https://github.com/edewit> is doing in iOS but, I don't like the idea of
> copy the source code.
>
> [image: :-1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-cordova-oauth2/pull/17#issuecomment-78287588>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by abstractj** [comment]
@edewit the maintenance to keep the codebase up to date and in sync with AGDROID, is the reason of -1.

I have to agree with @danielpassos on it. To me the consensus would be:

1. Document the workaround like @edewit already did into the readme files.
2. Wait for aar support like @danielpassos mentioned.

**Comment by edewit** [comment]
@matzew @danielpassos for iOS we include the source as well and 'normal' cordova plugins do source includes as well. I don't see the problem either source or jar we still have to maintain a dependency manually.

@matzew for the push plugin we also have a jar dependency there is no way to have a automatic update.

**Comment by edewit** [comment]
even when android platform 4.0 is released the plugin will have to ship with the aar files included.

**Comment by bleathem** [comment]
IMO if you want people to adopt this plugin on Cordova-Android < 4 then removing the gradle workaround is necessary.  Having users change their build process because they installed a plugin is non-intuitive, and a blocker for adoption.

**Comment by matzew** [comment]
Ok... on other plugins, we simply include the JAR files:
https://github.com/aerogear/aerogear-cordova-push/tree/master/src/android/libs

but not the source code (.java files). Wjy cant we do that here ?

**Comment by edewit** [comment]
@matzew we can't do that here because there is layout included

**Comment by matzew** [comment]
@edewit I am sorry but I don't understand what "layout included" means

**Comment by edewit** [comment]
@matzew the lib. contains a dialog that is layout it needs resource xml file that generates a source file called R.java aar files are a [special format](http://tools.android.com/tech-docs/new-build-system/aar-format) that contains all that, But we can't use that because cordova doesn't support adding aar files so adding the sources and letting the build file do the generation off of the layout files is an alternative. I've included the jar dependencies for the other libs that don't have layout.

**Comment by matzew** [comment]
Ah! ok. thanks for clarification, @edewit 

Will, at some point, cordova support aar files?

**Comment by edewit** [comment]
rumor has it that version 4.0 of the android platform will support aar, but until that time let's have this source dependency.

**Comment by matzew** [comment]
> rumor has it that version 4.0 of the android platform will support aar, but until that time let's have this source dependency.

I agree with this, @edewit +1

**Pull request merged**
